AppBlog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    
    path('', inicio, name='inicio'),
    path('about/', aboutinfo, name='about'),
    path('error/', error),

    path('formulario/', formularioAutos, name='formulario'),

    #Busqueda   
    path('busqueda/', busquedaAutos, name='busqueda'),
    path('resultadobusqueda/', resultadoBusqueda),
    
    #Clases para CRUD
    path('listaAutos/', ListarAutos.as_view(), name='listaAutos'),
    path('detalleAuto/<int:pk>', DetalleAutos.as_view(), name='detalleAuto'),
    path('editarAuto/<int:pk>', EditarAutos.as_view(), name='editarAuto'),
    path('eliminarAuto/<int:pk>', EliminarAutos.as_view(), name='eliminarAuto'),

    #Usuarios
    path('login/', login_request, name='login'),
    path('logout/', LogoutView.as_view(template_name='AppBlog/logout.html'), name='logout'),
    path('registro/', register, name='registro'),
    path('editarusuario/', editarUsuario, name='editarusuario'),
    path('agregarAvatar', agregarAvatar, name='agregarAvatar'),


]

BlogAutos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppBlog/', include('AppBlog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AppBlog/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User

class Autos(models.Model):
    
    marca = models.CharField(max_length=40)
    modelo = models.CharField(max_length=40)
    año_de_fabricacion = models.IntegerField()
    descripcion = models.TextField(max_length=240, null=True, blank=True)
    imagen = models.ImageField(upload_to='imagenautos', null=True, blank=True)
    fecha_de_edicion = models.DateField()
    version = models.CharField(max_length=30)
    motorizacion = models.CharField(max_length=30)
    combustible = models.CharField(max_length=30)

    def __str__(self):

        return f" {self.marca} {self.modelo}" 


class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank=True)
    

AppBlog/forms.py
from socket import fromshare
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class FormuAutos(forms.Form):    #formulario para crear autos

    marca = forms.CharField()
    modelo = forms.CharField()
    version = forms.CharField(label = "Versión")
    año_de_fabricacion = forms.IntegerField(label = "Año de fabricación")
    motorizacion = forms.CharField(label = "Motorización")
    combustible = forms.CharField()
    descripcion = forms.CharField(label = "Descripción", widget=forms.Textarea)
    imagen = forms.ImageField()



class FormuRegisitro(UserCreationForm):   #formulario para el registro

    email = forms.EmailField()

    class Meta:

        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class EditarUsuario(UserCreationForm):     #Formulario para editar usuarios

    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repita la contraseña', widget=forms.PasswordInput)

    class Meta:

        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}


class FormuAvatar(forms.ModelForm):   #Formulario para agregar avatar al usuario

    class Meta:

        model = Avatar
        fields = ['imagen']

AppBlog/views.py
from datetime import date
from django.shortcuts import render
from .models import *
from .forms import *
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

def inicio(request):      #funcion para mostrar el inicio

    return render (request, 'AppBlog/inicio.html')



def aboutinfo (request):     #funcion para mostrar la información "acerca de"

    return render (request, 'AppBlog/about.html')


@login_required
def formularioAutos(request):   #funcion para mostrar el formulario para ingresar autos

    if request.method == 'POST':

        form = FormuAutos(request.POST, request.FILES)

        if form.is_valid():

            info = form.cleaned_data

            auto = Autos(marca=info['marca'], modelo=info['modelo'], año_de_fabricacion=info['año_de_fabricacion'], descripcion=info['descripcion'], fecha_de_edicion=date.today(), imagen=info['imagen'], version=info['version'], motorizacion=info['motorizacion'], combustible=info['combustible'])

            auto.save()

            return render (request, "AppBlog/inicio.html")

    else:

        form = FormuAutos()

    return render (request, 'AppBlog/formuautos.html', {"form": form})


@login_required
def busquedaAutos(request):     #funcion para mostrar formulario para buscar autos

    return render(request, "AppBlog/busqueda.html")


@login_required
def resultadoBusqueda(request):     #funcion para mostrar el resultado de la busqueda

    if request.GET['marca']:

        marca = request.GET['marca']

        auto = Autos.objects.filter(marca__icontains=marca)

        return render (request, 'AppBlog/resultadoBusq.html', {"auto": auto, "marca": marca})

    else:
        
        return render(request, 'AppBlog/error.html',)



def error(request):    #funcion para mostrar error al no ingresar datos en al busqueda

    return render(request, 'AppBlog/error.html')



class ListarAutos(ListView):        #clase para listar autos

    model = Autos
    template_name = "AppBlog/listaAutos.html"



class DetalleAutos(DetailView):      #clase para mostrar detalles

    model = Autos
    template_name = "AppBlog/detalleAutos.html"



class EditarAutos(LoginRequiredMixin, UpdateView):        #clase para editar los autos

    model = Autos
    success_url = "/AppBlog/listaAutos"
    fields = ["marca", "modelo", "version", "año_de_fabricacion", "motorizacion", "combustible", "descripcion", 'imagen']
    template_name = "AppBlog/edicionAutos.html"



class EliminarAutos(LoginRequiredMixin, DeleteView):

    model = Autos
    success_url = "/AppBlog/listaAutos"
    template_name = "AppBlog/eliminarautos.html"



def login_request(request):      #funcion para el login

    if request.method == 'POST':

        form = AuthenticationForm(request, data = request.POST)

        if form.is_valid():

            usuario = form.cleaned_data.get('username')
            contra = form.cleaned_data.get('password')

            user = authenticate(username = usuario, password = contra)

            if user:

                login(request, user)

                return render(request, "AppBlog/inicio.html", {"mensaje": f"Bienvenido {user}"})
        
        else:

            return render (request, "AppBlog/inicio.html", {"mensaje": "Error en los datos ingresados."})

    else:

        form = AuthenticationForm()

    return render (request, "AppBlog/login.html", {"form": form})



def register(request):     #funcion para crear registro

    if request.method == "POST":

        form = FormuRegisitro(request.POST)

        if form.is_valid():

            username = form.cleaned_data['username']
            
            form.save()

            return render (request, "AppBlog/inicio.html", {"mensaje": "Usuario creado con éxito"})

    else:

        form = FormuRegisitro()

    return render (request, "AppBlog/registro.html", {"form": form})



def editarUsuario(request):   #funcion para editar el usuario

    usuario = request.user

    if request.method == 'POST':

        miFormu = EditarUsuario(request.POST)

        if miFormu.is_valid():

            info = miFormu.cleaned_data

            usuario.email = info['email']
            usuario.first_name = info['first_name']
            usuario.last_name = info['last_name']
            usuario.password1 = info['password1']
            usuario.password2 = info['password2']

            usuario.save()

            return render (request, "AppBlog/inicio.html")

    else:

        miFormu = EditarUsuario(initial={'first_name':usuario.first_name, 'last_name': usuario.last_name, 'email': usuario.email})

    return render (request, "AppBlog/editarUsuario.html", {"miFormu": miFormu, "usuario": usuario})



@login_required
def agregarAvatar(request):    #Función para agregar foto al perfil del usuario

    if request.method == 'POST':

        miFormu = FormuAvatar(request.POST, request.FILES)

        if miFormu.is_valid():

            usuario = User.objects.get(username=request.user)

            avatar = Avatar (user=usuario, imagen=miFormu.cleaned_data['imagen'])

            avatar.save()

            return render(request, "AppBlog/inicio.html")

    else:

        miFormu = FormuAvatar()

    return render (request, 'AppBlog/agregarAvatar.html', {"miFormu": miFormu})

AppBlog/templates/AppBlog/about.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Acerca de mí

{% endblock %}


{% block texto %}

<p>Mi nombre es Agustín González Vilas.</p>
<p>Tengo 27 años. Soy de Buenos Aires, Argentina.</p>
<p>Me encanta programar y amo todo lo relacionado con la tecnología.</p>
<p>Este es mi proyecto final para el curso de Python de CoderHouse.</p>


{% endblock %}

AppBlog/templates/AppBlog/agregarAvatar.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Agregar avatar

{% endblock %}


{% block texto %}

<form action="" enctype="multipart/form-data" method='POST'> {% csrf_token %}

    <table>

        {{miFormu.as_table}}

    </table>

    <input type="submit" value="Guardar">

</form>

{% endblock %}

AppBlog/templates/AppBlog/busqueda.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Búsqueda de autos

{% endblock %}


{% block texto %}

<p>Ingrese la marca del auto que desea buscar:</p>

<form action="/AppBlog/resultadobusqueda/" method='GET'> {% csrf_token %}

    <input type="text" name="marca">
    <input type="submit", value="Buscar", id="Buscar">

</form>


{% endblock %}

AppBlog/templates/AppBlog/detalleAutos.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Detalle del auto seleccionado

{% endblock %}


{% block texto %}

<p> <b>Marca:</b>  {{autos.marca}}</p>
<p> <b>Modelo:</b>  {{autos.modelo}}</p>
<p> <b>Versión:</b>  {{autos.version}}</p>
<p> <b>Año de fabricación:</b>  {{autos.año_de_fabricacion}}</p>
<p> <b>Motorización:</b>  {{autos.motorizacion}}</p>
<p> <b>Combustible:</b>  {{autos.combustible}}</p>
<p> <b>Descripción:</b>  {{autos.descripcion}}</p>
<img src="{{autos.imagen.url}}" style="max-width: 500px">

<p> <em>Fecha de creación: {{autos.fecha_de_edicion}}</em> </p>


{% endblock %}

AppBlog/templates/AppBlog/editarUsuario.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Editar usuario

{% endblock %}


{% block texto %}

<form action="" method="POST"> {% csrf_token %}

    <table>

        {{miFormu.as_table}}

    </table>

    <input type="submit" value="Editar">

</form>

{% endblock %}

AppBlog/templates/AppBlog/eliminarautos.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Eliminar auto seleccionado

{% endblock %}


{% block texto %}

<form action="" method="POST"> {% csrf_token %}

¿Seguro desea eliminar el auto seleccionado?
<p><input type="submit" value="Eliminar"></p>
    


{% endblock %}

AppBlog/templates/AppBlog/error.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Error

{% endblock %}


{% block texto %}

<p>No ingresaste datos</p>

{% endblock %}

AppBlog/templates/AppBlog/formuautos.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Formulario para ingresar autos

{% endblock %}


{% block texto %}

<p>En el siguiente formulario podrás ingresar los datos del auto:</p>

<form action="" enctype="multipart/form-data" method='POST'> {% csrf_token %}

    <table>

        {{form.as_table}}

    </table>

    <input type="submit", value="Enviar">

</form>


{% endblock %}

AppBlog/templates/AppBlog/inicio.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

¡Bienvenido al blog de autos!

{% endblock %}


{% block texto %}

<p>En esta página podrás encontrar mucha información con respecto a todo tipo de autos.</p>
<p>Una vez registrado podrás cargar los datos de tus autos preferidos.</p>

<b>{{mensaje}}</b>



{% endblock %}

AppBlog/templates/AppBlog/listaAutos.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Lista de los autos guardados

{% endblock %}


{% block texto %}

{% for auto in object_list %}

    <li><b>{{auto.marca}} {{auto.modelo}}</b> </li>         
    <em>
        <a href="{% url 'detalleAuto' auto.id %}">Detalles</a>
        <a href="{% url 'editarAuto' auto.id %}">Editar</a>
        <a href="{% url 'eliminarAuto' auto.id %}">Eliminar</a>
    </em>

{% endfor %}

{% endblock %}

AppBlog/templates/AppBlog/logout.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Cerrar sesión

{% endblock %}


{% block texto %}

Has cerrado sesión.

{% endblock %}

AppBlog/templates/AppBlog/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog de Autos 🚗</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'AppBlog/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppBlog/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">Blog de autos</div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'listaAutos' %}">Lista de autos</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'formulario' %}">Formulario</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'busqueda' %}">Buscar autos</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'about' %}">Acerca de mi</a>
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">Menu Lateral</button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                {% if request.user.is_authenticated %}
                                <li class="nav-item active"><a class="nav-link"><b>Hola {{user}}</b></a></li>
                                {% with first_image=user.avatar_set.first %}
                                <img src="{{first_image.imagen.url}}" style="max-width: 50px">
                                {% endwith %}
                                {% endif %}
                                <li class="nav-item active"><a class="nav-link" href="{% url 'inicio' %}">Inicio</a></li>
                                {% if not request.user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'registro' %}">Registrarse</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a></li>
                                {% endif %}
                                {% if request.user.is_authenticated %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Usuario</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{% url 'editarusuario' %} ">Editar usuario</a>
                                        <a class="dropdown-item" href="{% url 'agregarAvatar' %}">Agregar avatar</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                                    </div>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                    <h1 class="mt-4">

                        {% block titulo %}

                        {% endblock %}

                    </h1>
                    <p>
                        {% block texto %}

                        {% endblock %}

                    </p>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'AppBlog/js/scripts.js' %}"></script>
    </body>
</html>

AppBlog/templates/AppBlog/registro.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Registro

{% endblock %}


{% block texto %}

<form action="" method="POST"> {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="Registrarse">

</form>

{% endblock %}

AppBlog/templates/AppBlog/resultadoBusq.html
{% extends 'AppBlog/padre.html' %}

{% block titulo %}

Búsqueda de autos

{% endblock %}


{% block texto %}

<p> <b>Estamos buscando el auto con la marca: {{marca}}</b>  </p>

{% if not auto %}

No existe en la base de datos la marca: {{marca}}

{% endif %}


{% for a in auto %}
<br>
<p> <b>Marca: </b> {{a.marca}}</p>
<p> <b>Modelo: </b> {{a.modelo}}</p>
<p> <b>Versión:</b>  {{a.version}}</p>
<p> <b>Año de fabricación:</b>  {{a.año_de_fabricacion}}</p>
<p> <b>Motorización:</b>  {{a.motorizacion}}</p>
<p> <b>Combustible:</b>  {{a.combustible}}</p>
<p> <b>Descripción:</b>  {{a.descripcion}}</p>
<img src="{{a.imagen.url}}" style="max-width: 500px">

<p> <em>Fecha de creación: {{a.fecha_de_edicion}}</em> </p>
    

{% endfor %}

{% endblock %}